 <asp:CheckBox ID="Check0" Text="0" runat="server" OnCheckedChanged="checkboxs" AutoPostBack="true" />
 <asp:CheckBox ID="Check1" Text="1" runat="server" OnCheckedChanged="checkboxs" AutoPostBack="true" />
 <asp:CheckBox ID="Check2" Text="2" runat="server" OnCheckedChanged="checkboxs" AutoPostBack="true" />
 <asp:CheckBox ID="Check3" Text="3" runat="server" OnCheckedChanged="checkboxs" AutoPostBack="true" />
 <asp:CheckBox ID="Check4" Text="4" runat="server" OnCheckedChanged="checkboxs" AutoPostBack="true" />
 <asp:CheckBox ID="Check5" Text="5" runat="server" OnCheckedChanged="checkboxs" AutoPostBack="true" />
 <asp:CheckBox ID="Check6" Text="6" runat="server" OnCheckedChanged="checkboxs" AutoPostBack="true" />
 <asp:CheckBox ID="Check7" Text="7" runat="server" OnCheckedChanged="checkboxs" AutoPostBack="true" />
 <asp:CheckBox ID="Check8" Text="8" runat="server" OnCheckedChanged="checkboxs" AutoPostBack="true" />
 <asp:CheckBox ID="Check9" Text="9" runat="server" OnCheckedChanged="checkboxs" AutoPostBack="true" />
 <asp:CheckBox ID="Check10" Text="10" runat="server" OnCheckedChanged="checkboxs" AutoPostBack="true" />
 <asp:CheckBox ID="Check11" Text="11" runat="server" OnCheckedChanged="checkboxs" AutoPostBack="true" />
 <asp:CheckBox ID="Check12" Text="12" runat="server" OnCheckedChanged="checkboxs" AutoPostBack="true" />
